#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$(readlink -f "$0")")"


ARGPARSE_DESCRIPTION="Edit the given DISK_IMAGE file dumped from the SD card of a Qingyun 1000 board."
source argparse.bash || exit 1
argparse "$@" <<EOF || exit 1
parser.add_argument('disk_image', help='path of the disk image file, i.e., ./qingyun.img')
parser.add_argument('-r', '--as-root', action='store_true', help='login to shell as root user after chroot')
EOF

if [[ ! -f "$DISK_IMAGE" ]]; then
    >&2 echo "The given disk image file '$DISK_IMAGE' does not exist!"
    exit 1
fi

dep_pkgs="qemu-user-static"
echo "Check if $dep_pkgs exist..."
if [[ $(dpkg -l dep_pkgs &> /dev/null) -ne 0 ]]; then
    echo "$dep_pkgs not found. Please install them with the package manager."
    exit 1
fi
echo "[OK]"

echo "Finding the first unused loop device..."
echo "sudo permission is required."
loop_dev="$(sudo losetup -f)"
echo "[OK]"
echo "Associating loop device '$loop_dev' with image file '$DISK_IMAGE'..."
sudo losetup --partscan "$loop_dev" "$DISK_IMAGE"
echo "[OK]"

# try
set +e; ( set -e;

    echo "Getting the partition info of '$loop_dev'..."
    lsblk "$loop_dev"
    partitions_num=$(($(lsblk -pno NAME,MOUNTPOINT "$loop_dev" | grep -c ' ')-1))
    if [[ "$partitions_num" -ne 3 ]]; then
        >&2 echo "The given disk image file '$DISK_IMAGE' must has 3 partitions!"
        exit 1
    fi

    root_mntpnt=$(mktemp -d)
    echo "Mounting '/' (${loop_dev}p1) partition to '$root_mntpnt'..."
    sudo mount "${loop_dev}p1" "$root_mntpnt"
    sudo mount --bind /dev  "${root_mntpnt}/dev"
    sudo mount --bind /sys  "${root_mntpnt}/sys"
    sudo mount --bind /proc "${root_mntpnt}/proc"
    sudo mount --bind /run  "${root_mntpnt}/run"
    echo "[OK]"

    copied_qemu=
    qemu_path=/usr/bin/qemu-aarch64-static
    if [[ ! -f "${root_mntpnt}/${qemu_path}" ]]; then
        sudo cp $qemu_path "${root_mntpnt}/${qemu_path}"
        copied_qemu=1
    fi

    # try
    set +e; ( set -e;

        user_after_chroot="HwHiAiUser"
        if [[ "$AS_ROOT" == 'yes' ]]; then
            user_after_chroot="root"
        fi
        cmd_after_chroot=" \
            set -e;
            . ~/.bashrc; \
            home_mntpnt=/home; \
            echo \"Mounting '/home' (${loop_dev}p3) partition to \$home_mntpnt...\"; \
            sudo mount \"${loop_dev}p3\" \"\$home_mntpnt\"; \
            echo \"[OK]\"; \
            echo \"========== Welcome to the inner world! ==========\"; \
            echo \"========== Press 'Ctrl-D' or execute 'exit' to quit. ==========\"; \
            set +e; ( set -e; su -l ${user_after_chroot} ); set -e; \
            echo \"========== Goodbye from the inner world! ==========\"; \
            echo \"Unmounting '/home' (${loop_dev}p3) partition from \$home_mntpnt...\"; \
            umount \"\$home_mntpnt\"; \
            echo \"[OK]\"; \
            "
        sudo chroot "${root_mntpnt}" qemu-aarch64-static /bin/bash -c "$cmd_after_chroot"

    # catch
    ); set -e;

    echo "Unmounting '/' (${loop_dev}p1) partition from '$root_mntpnt'..."
    if [[ $copied_qemu -eq 1 ]]; then
        sudo rm -f "${root_mntpnt}/${qemu_path}"
    fi
    sudo umount "${root_mntpnt}/dev"
    sudo umount "${root_mntpnt}/sys"
    sudo umount "${root_mntpnt}/proc"
    sudo umount "${root_mntpnt}/run"
    sudo umount "$root_mntpnt"
    rm -rf "$root_mntpnt"
    echo "[OK]"

# catch
); set -e;

echo "Detaching loop device '$loop_dev' from image file '$DISK_IMAGE'..."
sudo losetup -d "$loop_dev"
echo "[OK]"

echo "Script execution finished."
